# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - softwarefullgateway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore ProductComponent dependencies
        run: dotnet restore SoftwareFullComponents.Gateway/SoftwareFullComponents.Gateway.csproj 
      - name: Build ProductComponent
        run: dotnet build SoftwareFullComponents.Gateway/SoftwareFullComponents.Gateway.csproj --no-restore
      - name: Test ProductComponent
        run: dotnet test SoftwareFullComponents.Gateway/SoftwareFullComponents.Gateway.csproj --no-build --verbosity normal
        
  push-to-hub:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        tags: v1, latest
        # Name of the Docker image
        image: 3739323298328/web-gateway
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: SoftwareFullComponents.Gateway/Dockerfile
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'softwarefullgateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e1eb8e7f17f41a5939439ddf415b36e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_dd7952fa6fe9464fb7ea3fc35d178767 }}/3739323298328/web-gateway:${{ github.sha }}'
